### ISSUE TITLE
Unable to insert when passing value by reference to another function

### ISSUE THREAD

**Issue by heroin-moose** [kurtbuilds/ormlite#7]
Code:

```
use ormlite::Model;
use ormlite::model::*;
use sqlx::FromRow;
use sqlx::SqlitePool;

#[derive(Model, FromRow)]
struct Example {
    #[ormlite(primary_key)]
    id: i64
}

async fn insert(e: &Example, pool: &SqlitePool) -> ormlite::Result<Example> {
    e.insert(pool).await
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let pool = SqlitePool::connect("/tmp/database").await?;
    let e1 = Example { id: 20 };

    insert(&e1, &pool).await?;

    Ok(())
}
```

Error:

```
   Compiling ormlite-issue v0.1.0 (/tmp/ormlite-issue)
error[E0507]: cannot move out of `*e` which is behind a shared reference
  --> src/main.rs:13:5
   |
13 |     e.insert(pool).await
   |     ^^^^^^^^^^^^^^ move occurs because `*e` has type `Example`, which does not implement the `Copy` trait

For more information about this error, try `rustc --explain E0507`.
error: could not compile `ormlite-issue` due to previous error
```

**Comment by heroin-moose** [comment]
However, this works (given e implement Clone):

```
    e.clone().insert(pool).await
```

**Comment by kurtbuilds** [comment]
Using the code like this, you need to use `Clone`.

The query depends on the `Example` because it needs to populate the query parameters. Since you're only borrowing it, the compiler can't guarantee that the `&Example` lives as long as the query.

You can solve this by moving example into your `insert`, or `clone`ing `e`, as you did.

**Comment by heroin-moose** [comment]
You mean the query has the lifetime of pool?

**Comment by heroin-moose** [comment]
Because raw query works, e.g. this compiles ok:

```
async fn explicit_insert(e: &Example, pool: &SqlitePool) -> sqlx::Result<()> {
    sqlx::query("INSERT INTO example (id) VALUES ($1)")
        .bind(&e.id)
        .execute(pool)
        .await?;
    Ok(())
}
```

I still pass the id by reference but compiler is happy. Am I missing something obvious?

**Comment by kurtbuilds** [comment]
> You mean the query has the lifetime of pool?

Not exactly. In your function, `e` and `pool` have different (unspecified) lifetimes.

`ormlite::Model.insert` creates a `::sqlx::QueryAs` which takes the model's fields as borrowed arguments. Importantly, the binding happens asynchronously, because it happens inside the `Model.insert` function. Which is why the compiler complains about `&Example`. If you move it `fn insert(e: Example, ...)`, or clone it, this issue should go away.

In your second post, you manually do the binding, thus the binding happens synchronously, and the problem goes away.

**Comment by heroin-moose** [comment]
Thanks for the details!
